config/routes.rb
Rails.application.routes.draw do
  get 'rooms/index'
  resources :friends
  resources :comments
  resources :posts
  resources :rooms do
    resources :messages
  end

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "users#show"

  get '/search' => 'users#search'
  post '/add_friend/:friend_id/:user_id' => 'friends#create', as: 'add_friend'
  get '/:id' => 'users#show', as: 'profile'
  post '/comments/:post_id' => 'comments#create', as: 'add_comment'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Social</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <style>
      <%= ".msg-#{current_user&.id}" %> {
      background-color: #007bff !important;
      padding: 10px;
      }
      <%= ".cont-#{current_user&.id}" %> {
      display: flex;
      justify-content: flex-end
      }
    </style>
  </head>

  <body>
    <section class="container">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Social</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="<%= root_path %>">My page</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="<%= friends_path %>">Friends</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="<%= rooms_path %>">Chat rooms</a>
              </li>
              <li class="nav-item">
                <%= link_to 'Sign out', destroy_user_session_path, data: {turbo_method: :delete}, class: 'nav-link' %>
              </li>
            </ul>
            <%= form_tag(search_path, method: :get, class: 'd-flex') do %>
              <%= text_field_tag :search, nil, placeholder: "Search your friend", class: 'form-control me-2' %>
              <%= submit_tag "Search", class: 'btn btn-outline-success' %>
            <% end %>
          </div>
        </div>
      </nav>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </section>
  </body>
</html>